version: '3'
services:
  nginx:
    image: nginx     # 镜像名称
    container_name: nginx     # 容器名字
    restart: always     # 开机自动重启
    ports:     # 端口号绑定（宿主机:容器内）
      - '80:80'
      - '443:443'
    volumes :
      - /data/nginx/conf.d/:/etc/nginx/conf.d
      - /data/xjkj/:/xjkj/
