// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"xunjikeji.com.cn/gateway/app/interior/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/interior/protocol/deploy",
				Handler: protocolDeployHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/interior/protocol/stop",
				Handler: protocolStopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/interior/protocol/delete",
				Handler: protocolDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/interior/heart/beat",
				Handler: heartBeatHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/external/protocol/readtest",
				Handler: protocolReadTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gateway/external/protocol/writetest",
				Handler: protocolWriteTestHandler(serverCtx),
			},
		},
	)
}
